version: '3'

services:
  client:
    image: 'robingoood/open-code-frontend:1.0'
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - /app
      - /app/node_modules
    stdin_open: true
    tty: true
  service:
    image: 'robingoood/open-code-backend:1.3'
    container_name: 'bank-info-app'
    ports:
      - '8081:8081'